### ISSUE TITLE
Certaines étapes nécessitent un refresh de la page

### ISSUE THREAD

**Issue by GerardPaligot** [GDG-Lille/cms4partners#243]
Pour certaines étapes (la validation d'un partenaire par exemple), nécessite de refresh la page pour voir la prochaine étape accessible et les documents générés dans l'étape précédente.

Visuel quand je viens de valider un partenaire

<img width="1237" alt="Capture d’écran 2022-11-03 à 21 22 00" src="https://user-images.githubusercontent.com/1913901/199826186-75480a31-2a79-4a76-b1c1-14b7ee3139e1.png">

Après le refresh

<img width="1227" alt="Capture d’écran 2022-11-03 à 21 22 40" src="https://user-images.githubusercontent.com/1913901/199826290-12fd6201-d6fb-406d-a013-37171e80ed1d.png">

**Comment by EmmanuelDemey** [comment]
done
