### ISSUE TITLE
Permettre à un partenaire de laisser les orgas écrire la communication

### ISSUE THREAD

**Issue by GerardPaligot** [GDG-Lille/cms4partners#244]
Certains partenaires ne souhaitent pas forcément écrire la communication, il faudrait donc ajouter un bouton "Skip" ou "Laissez les orgas gérer".

**Par contre, si l'étape de communication est skip, ça serait bien d'avoir à minima 2 champs obligatoires : le lien vers le compte Twitter et vers le LinkedIn. Histoire de savoir qui ping dans nos messages**

**Comment by EmmanuelDemey** [comment]
done
