### ISSUE TITLE
Pouvoir renseigner les codes billet web des partenaires via le cms

### ISSUE THREAD

**Issue by GerardPaligot** [GDG-Lille/cms4partners#247]
A la dernière étape, en tant que orga, on devrait pouvoir renseigner le code du partenaire.

Le message à l'étape de validation du paiement sera a changé du coup :

> Une fois cet étape validée, une étape manuelle est nécessaire. elle consiste à générer les codes dans Billetweb et les ajouter dans la console Firebase.

**Comment by EmmanuelDemey** [comment]
done
