### ISSUE TITLE
Ajouter une description dans les informations d'une entreprise

### ISSUE THREAD

**Issue by GerardPaligot** [GDG-Lille/cms4partners#249]
La description doit être assez courte, il faudrait mettre une limite de caractères.
A vue de nez, quelque chose comme 140 caractères devrait être suffisant.

**Comment by EmmanuelDemey** [comment]
@GerardPaligot peux tu me dire quel est l'intéret de ce champ ? C'est pour donner un peu de context sur le CMS.

**Comment by GerardPaligot** [comment]
Je sais pas si c'est envisageable pour toi sur le site mais côté application, j'aimerais travail un écran dédié au partenaire avec toutes leurs infos plutôt qu'une simple liste de logo cliquable.

Mais peut-être que c'est pas l'objectif de cms4partners ? 🤔

**Comment by EmmanuelDemey** [comment]
donc ce sera utilisé dans l'application mobile pour présenter la société ?

**Comment by EmmanuelDemey** [comment]
done
