### ISSUE TITLE
Ajouter la latitude et la longitude des adresses des partenaires

### ISSUE THREAD

**Issue by GerardPaligot** [GDG-Lille/cms4partners#250]
**Query Autocomplete**

Aiider les partenaires à remplir leur champs d'adresse.

Documentation : [Link](https://developers.google.com/maps/documentation/places/web-service/query)
Curl :
```bash
curl --location --request GET 'https://maps.googleapis.com/maps/api/geocode/json?address=1 Bd des Cités Unies&key=$API_KEY'
```

**Geocoding**
Récupérer la latitude / longitude de l'adresse du partenaire.

Documentation : [Link](https://developers.google.com/maps/documentation/geocoding/requests-geocoding#geocoding-lookup)
Curl :
```bash
curl --location --request GET 'https://maps.googleapis.com/maps/api/place/queryautocomplete/json?input=1 Bd des Cités&key=$API_KEY'
```

**Pricing**

Documentation : [Link](https://mapsplatform.google.com/pricing/?_gl=1*1tbbuo*_ga*MjExOTEzOTcxNC4xNjY2MTEyMDc3*_ga_NRWSTWS78N*MTY2ODE5NTQ0OS4xLjEuMTY2ODE5NTc1MS4wLjAuMA..)

Gratuit les 200 premiers dollars puis

Geocoding : 5$ pour 1000 requêtes
Autocomplete : 2,83 pour 1000 requêtes

**Comment by EmmanuelDemey** [comment]
done
