### ISSUE TITLE
Les partenaires ne voient pas la case à cocher pour nous laisser gérer la communication

### ISSUE THREAD

**Issue by GerardPaligot** [GDG-Lille/cms4partners#315]
Après un mail d'un de nos partenaires, il semblerait qu'ils ne voient pas la checkbox dans la section communication.
Bizarrement, je vois la case en version admin ou partenaire.

**Bug**
![image](https://user-images.githubusercontent.com/1913901/218555827-9721d22c-87e4-418f-a82f-0000d5d5a5b2.png)

**Expected**
<img width="982" alt="Capture d’écran 2023-02-13 à 20 33 53" src="https://user-images.githubusercontent.com/1913901/218556200-ccd9f116-fab5-4c9e-bd11-c86280259b9d.png">

**Comment by EmmanuelDemey** [comment]
Normal. car ce sont des sponsors virtuels.
