### ISSUE TITLE
Faire un design pour visualiser les etapes du partenariat

### ISSUE THREAD

**Issue by EmmanuelDemey** [GDG-Lille/cms4partners#34]
- En lecture seule pour le partenaire
- Avec des boutons pour activer/desactiver pour les admins

**Comment by EmmanuelDemey** [comment]
etapes : 
- Partenariat rempli
- Partenariat validé
- Convention signé
- Paiment reçu
- Messages  reseaux sociaux recus
- Communication faite

**Comment by T3kstiil3** [comment]
WIP 
![image](https://user-images.githubusercontent.com/3717296/67744785-bab88e00-fa22-11e9-8d68-e14e552aaa4d.png)

**Comment by EmmanuelDemey** [comment]
Tu veux qu'on merge ?
